### ISSUE TITLE
Tool to validate customer environment prior to installing hybrid cloud

### ISSUE THREAD

**Issue by djptek** [qdrant/qdrant-cloud-support-tools#11]
@bashofmann might there be value in a tool to validate the customer environment before they install hybrid cloud?

- the tool could interrogate the local system to check for the [prerequisites](https://qdrant.tech/documentation/hybrid-cloud/hybrid-cloud-setup/#prerequisites) and generate appropriate warnings before the customer commences an install that may result in an unusable &/or unhealthy cluster 
- the tool could be updated as and when we validate (or contraindicate) environments to host the remote clusters

**Comment by bashofmann** [comment]
Added in https://github.com/qdrant/qdrant-cloud-support-tools/tree/main/hybrid-cloud-prerequisites
